### PR TITLE
Add Presence Support

### PR DESCRIPTION
**Pull request by knewter**
- Add tests, initial syncState, syncDiff.
- Use an updated dict merge function, because of this bug in Elm's
  Dict.Merge: https://github.com/elm-lang/core/pull/648
- Parameterize user payloads
- Add documentation for Presence

### CODE REVIEW

**Comment by mxgrn** [comment]
Thanks for your work @knewter! I put your `Phoenix.Presence` module directly into my code, and it works well.

**Comment by praveenperera** [comment]
@fbonetti Is there an ETA of when this might be merged?

**Comment by dustinfarris** [comment]
@fbonetti this has been sitting here for 8 months, please update

**Comment by fbonetti** [comment]
Hey guys, sorry for being unresponsive for so long. I don't have time to maintain this project. If anyone would like to take ownership, I'd be happy to give you access to the repo.

**Comment by maxstr** [comment]
Thanks for this and sorry for the wait! I've reviewed, updated, and merged it. 

I'd like to add some more "transparent" mechanisms for tracking presence in the future, but I appreciate you were following the JS library.

**Pull request closed without merging**
